### ISSUE TITLE
[Q/A] Shared file system

### ISSUE THREAD

**Issue by balazsfabian** [LLNL/merlin#271]
## 🤓 Question

When running Merlin of different machines, a shared file system must be created.
* What is the recommended method for setting up this file system, across several machines, possibly some HPC? I have tried Network File System which works, but I'm not sure whether this is the best option.
* Another aspect of this, is the directory tree. When I mount the NFS directory on two machines, not only the Merlin directories must be shared, but the _whole_ path must be exactly the same, even above the mount point. I have tried using `OUTPUT_PATH` set from an env variable to overcome this, but apparently its value is substituted before the task is passed to the worker.

**Comment by koning** [comment]
Thanks for the question.  The main parallel filesystem we have the most experience with is lustre, http://lustre.org/, other filesystems we have used are GPFS, https://www.ibm.com/support/knowledgecenter/SSFKCN/gpfs_welcome.html,  and a new system coming online from Vast, https://vastdata.com/ . There are several other parallel filesystems as well that you can read about here: https://en.wikipedia.org/wiki/Clustered_file_system

In general, we do not use NFS because there is a delay in synchronization on a cluster that may cause issues with the remote tasks. 

All of our prototype multi-machine runs use a common file system entry point so there is not mechanism currently to change the path prepending the top level output path.
