### ISSUE TITLE
[BUG] [SSIA] Merlin job doesn't exit on failure or completion before allocated time

### ISSUE THREAD

**Issue by samadejacobs** [LLNL/merlin#277]
SSIA

**Comment by lucpeterson** [comment]
Can you add some context to this? Which 'job'? The batch job? The step? What does your workflow step look like?

**Comment by ben-bay** [comment]
I assume this is related to `merlin monitor`?

**Comment by samadejacobs** [comment]
When you submit a (_LBANN_) job through merlin and bsub, if that job failed (for whatever reason) or completed before requested allocated (_BSUB -W_) time, merlin does not exit queue as would be done normally if the job is submitted without merlin. This happens with or without _merlin monitor_ . 

Example of my bsub file:
#!/bin/bash
#BSUB -nnodes 8
#BSUB -W 2:00    # hours:minutes

YAML=train_atom.yaml

VENV_NAME=merling_lassen_venv

# Activate the virtual environment
source ${MERLIN_PATH}/${VENV_NAME}/bin/activate

merlin stop-workers ${YAML} 
merlin purge -f ${YAML}
# Send all tasks to the broker
merlin run ${YAML}

# Show the workers command
merlin run-workers ${YAML} --echo

# Start workers to run the tasks in the broker
merlin run-workers ${YAML}

# Keep the allocation alive until all workers stop
merlin monitor ${YAML}

**Comment by ben-bay** [comment]
Okay, so your allocated bsub job doesn't end early even though the workflow itself has failed. When you aren't using `merlin monitor`, are you using `sleep inf` instead? Because that will indefinitely block, stopping the job from ending early.

**Comment by samadejacobs** [comment]
I guess I have tried both _merlin monitor_ and _sleep inf_ in the past and still same problem.

**Comment by ben-bay** [comment]
Right. With either of these, the allocation will continue indefinitely to walltime (sleep inf) or even possibly exit earlier than desired (merlin monitor). That is the expected behavior for sleep inf. @lucpeterson correct me if I'm wrong, but right now, because of a bug in celery, there isn't a perfect working solution for using merlin to dynamically stop allocated jobs early.

**Comment by ben-bay** [comment]
However we are working on this. A refactor I'm working on now may indeed clear the way for this to be debugged so `merlin monitor` can work as expected.

**Comment by koning** [comment]
With merlin monitor the allocation would still persist since there are still tasks in the queue. This sounds like a request for new monitor functionality that will check for the case where there are tasks in the queue but the workers are not running any tasks but have run tasks recently (error condition).

**Comment by samadejacobs** [comment]
Ok, please ping me when this is fixed or the functionality is available.
