### ISSUE TITLE
[BUG]  new “merlin status” on old workflows 

### ISSUE THREAD

**Issue by lucpeterson** [LLNL/merlin#469]
## Bug Report

**Describe the bug**
It looks like if you run the new “status” command on a workflow that was run with old merlin, it will just hang as it searches for the status files. 

**To Reproduce**
1. Run a workflow with an older version of merlin
2. Call merlin status on that with the newer version

**Expected behavior**
Some kind of warning, a direction to use the old command, and a graceful exit

**Comment by bgunnar5** [comment]
So that I can keep track of them all, I'm adding on to this thread with a few additional bugs with the status command that I've encountered:

1. When a step is only using one sample, the status file is still "condensed" but then the file is just removed so you can't view the status of that step at all
2. The worker for a step is expected to be just a single worker, however several workers can process a single step (think restarting a step or multiple workers processing the same step). When multiple workers process a step, the statuses cannot be condensed properly and can cause a workflow to fail
3. For dry runs, the name has a typo when trying to render the progress bar

**Comment by bgunnar5** [comment]
@lucpeterson I'm looking into the bug you mentioned now but I'm unable to reproduce. When I run a study with merlin v1.11.1 and then try to check the status with merlin v1.12.0 it just shows empty progress bars:
![image](https://github.com/LLNL/merlin/assets/49216024/a4448d38-d166-4fd8-b5e8-42c11e462124)

Which study were you running that caused this? Maybe there's a certain case where this happens but won't otherwise

**Comment by lucpeterson** [comment]
This was not actually a problem
